version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gocritic
    - godot
    - gosec
    - misspell
    - nakedret
    - paralleltest
    - perfsprint
    - staticcheck
    - tagalign
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    cyclop:
      max-complexity: 12
      package-average: 0
    perfsprint:
      errorf: true
      strconcat: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
