name: Code Check

on: [push, pull_request]

jobs:
  code-check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.23.x"]

    name: code-check

    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: 01_Checkout_Code
        uses: actions/checkout@v4

      - name: 02_Install_Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: 03_Format_Code
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          make fmt

      - name: 04_Lint_Check
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: 05_Initialize_CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'go'
          queries: +security-and-quality

      - name: 06_Auto_Build
        uses: github/codeql-action/autobuild@v2

      - name: 07_CodeQL_Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:go"
